// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("LemonadeEncodingProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("LemonadeEncodingProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing LemonadeEncodingProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "LemonadeEncodingProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "LemonadeEncodingProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing LemonadeEncodingProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
